# Generated by Django 5.1.2 on 2024-10-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo_team',
            name='team_role',
            field=models.CharField(choices=[('PL', 'Player'), ('CM', 'Coach/Mentor'), ('TL', 'Team Leader')], default='PL', max_length=2),
        ),
    ]
