# Generated by Django 5.1.2 on 2024-10-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playermasteravailability_playerteamavailability'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playermasteravailability',
            name='unique_master_availability',
        ),
        migrations.RemoveConstraint(
            model_name='playerteamavailability',
            name='unique_team_availability',
        ),
        migrations.RenameField(
            model_name='playermasteravailability',
            old_name='playerinfo',
            new_name='player_info',
        ),
        migrations.RenameField(
            model_name='playerteamavailability',
            old_name='playerinfo_team',
            new_name='player_info_team',
        ),
        migrations.AddConstraint(
            model_name='playermasteravailability',
            constraint=models.UniqueConstraint(fields=('player_info', 'start_time'), name='unique_master_availability'),
        ),
        migrations.AddConstraint(
            model_name='playerteamavailability',
            constraint=models.UniqueConstraint(fields=('player_info_team', 'start_time'), name='unique_team_availability'),
        ),
    ]
