"""Add column players_teams_availability.availability

Revision ID: 062a154a0797
Revises: 4fb63c11ee8c
Create Date: 2024-10-30 23:54:22.877218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062a154a0797'
down_revision = '4fb63c11ee8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_teams_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.Integer(), nullable=False, default=2))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_teams_availability', schema=None) as batch_op:
        batch_op.drop_column('availability')

    # ### end Alembic commands ###
