"""Add PlayerEvent models

Revision ID: 131efbdd7af4
Revises: 1fc9a051a0a6
Create Date: 2024-11-19 10:16:34.289124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131efbdd7af4'
down_revision = '1fc9a051a0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_discord_integrations', schema=None) as batch_op:
        batch_op.alter_column('webhook_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_discord_integrations', schema=None) as batch_op:
        batch_op.alter_column('webhook_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
