"""Make players.discord_id unique

Revision ID: 251a8108d7ff
Revises: f4330df94c44
Create Date: 2025-05-14 16:44:16.817690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251a8108d7ff'
down_revision = 'f4330df94c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_players_discord_id", ['discord_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint("uq_players_discord_id", type_='unique')

    # ### end Alembic commands ###
