"""empty message

Revision ID: 273f73c81783
Revises: ce676db8c655
Create Date: 2024-10-29 23:12:40.743611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273f73c81783'
down_revision = 'ce676db8c655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_session',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.steam_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_session')
    # ### end Alembic commands ###
