"""Add event.discord_message_id

Revision ID: 286ee26b9e5d
Revises: 392454b91293
Create Date: 2024-11-25 21:00:08.444434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286ee26b9e5d'
down_revision = '392454b91293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_message_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('discord_message_id')

    # ### end Alembic commands ###
