"""Change integrations to one-to-one

Revision ID: 392454b91293
Revises: f802d763a7b4
Create Date: 2024-11-25 18:36:15.293593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392454b91293'
down_revision = 'f802d763a7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_discord_integrations',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('webhook_bot_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('team_logs_tf_integrations',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('logs_tf_api_key', sa.String(), nullable=True),
    sa.Column('min_team_member_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_logs_tf_integrations')
    op.drop_table('team_discord_integrations')
    # ### end Alembic commands ###
