"""Add team.discord_webhook_url

Revision ID: 958df14798d5
Revises: 062a154a0797
Create Date: 2024-10-31 09:56:43.335627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958df14798d5'
down_revision = '062a154a0797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_webhook_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('discord_webhook_url')

    # ### end Alembic commands ###
