"""Add auth_session.key

Revision ID: a340b3da0f2a
Revises: 273f73c81783
Create Date: 2024-10-29 23:17:29.296293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a340b3da0f2a'
down_revision = '273f73c81783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=31), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_column('key')

    # ### end Alembic commands ###
