"""Add webhook profile picture

Revision ID: c242e3f99c64
Revises: 286ee26b9e5d
Create Date: 2024-11-27 10:40:39.027786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c242e3f99c64'
down_revision = '286ee26b9e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_discord_integrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_bot_profile_picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_discord_integrations', schema=None) as batch_op:
        batch_op.drop_column('webhook_bot_profile_picture')

    # ### end Alembic commands ###
