"""Add players.discord_id field

Revision ID: f4330df94c44
Revises: f8588cdf998e
Create Date: 2025-05-14 14:06:29.368594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4330df94c44'
down_revision = 'f8588cdf998e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('discord_id')

    # ### end Alembic commands ###
