"""Rename table player to players

Revision ID: dcdb8fccde69
Revises: 4c2197a648ef
Create Date: 2024-10-23 15:33:02.447366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdb8fccde69'
down_revision: Union[str, None] = '4c2197a648ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.drop_table('player')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('steam_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.drop_table('players')
    # ### end Alembic commands ###
